### PR TITLE
Support file-specific Haxe configuration selection

### PR DESCRIPTION
**Pull request by Kallekro**
In our project we need to use multiple Haxe configurations as we have multiple targets, but we find it cumbersome to change it manually each time we switch files.

This tiny feature adds file-specific Haxe configuration selection. It is a completely transparent feature that don't have any impact if you don't use the feature explicitly. 

To use it you add a "magical comment" in the top of the haxe file which specifies the configuration by an identifier.

The configuration identifier can either be an hxml file:
```
// *-- config: build.hxml *--
class Main { ...
```

Or it can be the index of a configuration in the haxe.configuration array in settings.json:
```
// *-- config: 0 *--
class Main { ...
```

When the active editor changes, the first line is checked for a magical configuration comment and if it exists it will select it automatically. The user can of course still select another configuration and override the configuration comment if they like.

### CODE REVIEW

**Comment by Gama11** [comment]
Not a fan of this at first glance, I always imagined this feature would be implemented via an additional field in `haxe.configurations` where you can specify a glob pattern. That way the VSCode-specific stuff stays in VSCode config files, and you can also easily do this for entire packages. Otherwise, you'd have to put comments like this in every single .hx file in a directory I guess?

**Comment by Kallekro** [comment]
I must say I agree that this would be better. It's just a bit unfortunate that this would require a change in syntax, as the haxe.configuration field is an array and not a struct. That would mean the feature would not be transparent as it would require changing existing settings.json files.

**Comment by Gama11** [comment]
Not necessarily, you can express that in JSON schemas with `oneOf`, and on the Haxe side we could use `EitherType` in order to continue supporting both.

**Comment by Kallekro** [comment]
I see your point, and it looks like there is already support for using either lists or struct-like values in the haxe.configurations settings field.

**Comment by Gama11** [comment]
Oh right, we added support for `label` at some point.

**Pull request closed without merging**
