### PR TITLE
Show hex colors in gutter

### PR DESCRIPTION
**Pull request by RblSb**
Some idea from flutter extension. Not sure if it fits here.
image

### CODE REVIEW

**Comment by Gama11** [comment]
I like the general idea (wanted to implement something like this myself), but I'm not sure it's the right approach. The language server protocol actually has support for color stuff, where you then get fancy stuff like color pickers to edit the colors as well (plus it would be editor-independent of course).

https://microsoft.github.io/language-server-protocol/specification#textDocument_documentColor
https://microsoft.github.io/language-server-protocol/specification#textDocument_colorPresentation

Not quite sure what the difference between the two requests is at first glance / if both are needed.

**Comment by Simn** [comment]
I like this as well. \o/

**Comment by back2dos** [comment]
Would it be possible to do inline, as in css and its derivatives?

image

For one it won't collide with other gutter visuals (breakpoints, bookmarks, etc.) and also it's fine with multiple colors in a single line.

**Comment by Gama11** [comment]
@back2dos Pretty sure that's how it works if implemented via the LSP requests.

**Comment by RblSb** [comment]
https://github.com/vshaxe/haxe-language-server/pull/59

**Pull request closed without merging**
