### PR TITLE
Readme: add framework notes (see #18)

### PR DESCRIPTION
**Pull request by Gama11**
Not sure if it shoud be higher up or not. I guess if you're looking for it you'll find it.

### CODE REVIEW

**Comment by nadako** [comment]
I'd rather not call those files `build.hxml`, since that sounds misleading, how about `complete.hxml` or `display.hxml`? Also it's probably worth mentioning that these `.hxml` files should be added in as elements in the `haxe.displayConfigurations` array (that reminds me I should document configuration keys in README).

For Kha, I think it's more than that, IIRC it assumes that you're running from the `build` directory, not the workspace, so it should be something like `haxe.displayConfigurations: [["--cwd", "build", "project-<platform>.hxml"]]` to work properly. Also it's worth mentioning that you only get those files when you do a first build. (@RobDangerous does khamake has a function to generate the hxml file for completion without doing a build?)

**Comment by Gama11** [comment]
>I'd rather not call those files build.hxml, since that sounds misleading, how about complete.hxml or display.hxml

Yeah, that's a good point. I think "display" is more of an implementation-detaily name (since that's how the compiler internally calls it and all) and confusing to users. How about `completion.hxml`?

A can mention the stuff about Kha, but I don't really know anything about it.

**Comment by nadako** [comment]
`completion.hxml` sounds fine (even though it's technically not only completion)

**Comment by Gama11** [comment]
Should I make a special note for Flixel (that flixel-tools can be used to initialize the workspace?).

**Comment by RobDangerous** [comment]
No option to not build. But more importantly I'm pretty sure it should be `haxe.displayConfigurations: [["--cwd", "build/project-<platform>.hxml"]]`
Does adding more than one hxml do something meaningful?

**Comment by RobDangerous** [comment]
Thinking about it some more I'm pretty sure I was wrong about the thing I was pretty sure about.

**Comment by nadako** [comment]
> Does adding more than one hxml do something meaningful?

sure, if you want proper completion for different platforms or defines

**Comment by RobDangerous** [comment]
Cool. Have to try how that works exactly.

**Comment by nadako** [comment]
There'll be a menu in the statusbar when you open hx file having multiple configurations.

**Comment by nadako** [comment]
Thanks for this!

**Comment by Gama11** [comment]
You're not using squash-to-merge? Or did you just forget to enable it by default?

**Comment by nadako** [comment]
i think i used that one, but i guess not :)

**Pull request merged**
