### PR TITLE
Add folding markers to syntax configuration

### PR DESCRIPTION
**Pull request by KevinGliewe**
This PR adds the region markers `//#region` and `//#endregion` to add custom folding regions in the Haxe Code.
The snipped for the marker definition comes from the TypeScript configuration file in the VSCode repo:

https://github.com/Microsoft/vscode/blob/master/extensions/typescript/language-configuration.json#L28

I hope you guys like this feature. 

Example

### CODE REVIEW

**Comment by KevinGliewe** [comment]
Well, this is a strange build error... 🤔

**Comment by Gama11** [comment]
There was a discussion about this here: https://github.com/vshaxe/vshaxe/issues/179

**Comment by KevinGliewe** [comment]
Oh, sorry for the useless PR then.

**Comment by RealyUniqueName** [comment]
This feature is going t obe implemented in IDEA too: https://github.com/HaxeFoundation/intellij-haxe/pull/744
Maybe it should be treated as a convention.

**Comment by EricBishton** [comment]
IDEA is going to have two flavors available, at first:
 - An FD style: `// { region MyRegionTitle` and `// } endregion` (with spaces optional between the comment signifier and the bracket, between the brackets and the region marker -- because they aren't actually required for FD -- and and between "end" and "region").
 - An AS3 style: `// region MyRegionTitle` and `// end region` (again, the spaces are optional).

Eventually, the user will be allowed to specify starting and ending markers by providing regexes via a dialog.

**Comment by KevinGliewe** [comment]
Maybe we could use a regex as default which matches all the styles at once?

The start: 
` ^\s*\/[\/\*]\s*[#{]?\s*region\b`
https://regex101.com/r/3vWgnm/1

The end: 
` ^\s*\/[\/\*]\s*[#}]?\s*end ?region\b`
https://regex101.com/r/MPOk8s/1

Afterwards the pattern could be swapped out by a command or something along this line to use a specific style.
The method `vscode.setLanguageConfiguration(language: string, configuration: LanguageConfiguration): Disposable` should hopefully provide a way to accomplish it without reloading vscode.

*Note*:
 It looks like the documentation here is not up to date:
https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namelanguageconfigurationaspan-classcodeitem-id962languageconfigurationspan

There is no `folding` property in the documentation, but there is one in the sourcecode:
https://github.com/Microsoft/vscode/blob/777fddd4f7c65b4b1b040328b045c30c3c08f7bc/src/vs/editor/common/modes/languageConfiguration.ts#L68

**Comment by EricBishton** [comment]
Is the `#region` marker common in other languages/IDEs?  It seems that some folks like/expect it for JS.

**Comment by KevinGliewe** [comment]
I think the `#region` swapped over from C# to vscode. It looks like it is sort of convention now for vscode to fold using this marke. They even included it in Java.

https://github.com/Microsoft/vscode/blob/master/extensions/java/language-configuration.json#L27

**Comment by Gama11** [comment]
@nadako Any thoughts on this?

**Comment by nadako** [comment]
Not really, but this won't hurt I guess

**Comment by Gama11** [comment]
Since there's not really a convention, it would be strange to pick out one specific style to support. I'm going to use the @KevinGliewe's "match-all" regexes with support for:

- `// #region name` - `// #endregion`
- `// region name` - `// end region`
- `// { region name` - `// } endregion`

**Pull request closed without merging**
