### PR TITLE
Pass vscode version to lsp

### PR DESCRIPTION
**Pull request by RblSb**
See https://github.com/vshaxe/haxe-language-server/pull/120

### CODE REVIEW

**Comment by kLabz** [comment]
Can't we have a more editor agnostic field ?

**Comment by RblSb** [comment]
`forceCodeActionCommandResolveSupport:Bool`?

**Comment by kLabz** [comment]
Or just editor name + version?

**Comment by RblSb** [comment]
I don't get your suggestion. We can move my workaround to `forceCodeActionCommandResolveSupport: if (vscodeVersion >= 1.81.0)` on client, or pass current editor version like this to version checks on server.

**Comment by RblSb** [comment]
Can i merge it?

**Comment by kLabz** [comment]
Is the hack still needed with new versions ?

**Comment by RblSb** [comment]
Yea, this is lsp nodejs impl bug, not updated in vscode yet

**Pull request merged**
